jobs:
  - name: sample-eb-deploy-branch_runCI
    type: runCI
    steps:
      - OUT: app-image
      - OUT: app-version
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('

  - name: eb-deploy-master
    type: runCLI
    steps:
      - IN: master-branch
      - IN: aws-eb-bits
        switch: off
      - IN: app-version
      - TASK:
        - script: printenv
        - script: cd /build/IN/master-branch/gitRepo && eb init && eb deploy
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('
